### ISSUE TITLE
Na_1stOrder_splineContinuum

### ISSUE THREAD

**Issue by Jack-Rawlinson** [jancami/edibles#250]
Traceback (most recent call last):
  File "C:\Users\user\edibles\examples\Na_1stOrder_SplineContinuum.py", line 36, in <module>
    cont.add_to_csv(
  File "C:\Users\user\edibles\edibles\continuum.py", line 263, in add_to_csv
    csv_file = self.Spectrum.filename.replace(".fits", ".csv").replace(
TypeError: Path.replace() takes 2 positional arguments but 3 were given

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by alex-ebi** [comment]
replace method was used on pathlib.Path
Fixed it
